[package]
name = "hyperspace-rpc-rs"
version = "0.1.0"
authors = ["Timo Tiuraniemi <timo.tiuraniemi@iki.fi>"]

[dependencies]
protobuf = "=2.18.0"

[build-dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
protobuf-codegen-pure = "=2.18.0"
